name: typed_date_time
description: Adds additional types for Local and UTC Dates and DateTimes.
version: 0.1.0
author: Michael Schoonmaker <schoon@actionsprout.com>

environment:
  sdk: ">=2.1.0 <3.0.0"

dev_dependencies:
  test:
